name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    permissions:
      # Required by actions/checkout to clone the repository
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
