name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    permissions:
      # Required by actions/checkout to clone the repository
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: actions/checkout@v4
      - name: cache .yarn
        uses: actions/cache@v5
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-cache
      - name: Install
        run: nix develop -c yarn install
      - name: Build website
        run: nix develop -c yarn build
