# from https://docusaurus.io/docs/deployment#deploying-to-github-pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    permissions:
      # Required by peaceiris/actions-gh-pages to push the build output to the gh-pages branch
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cache .yarn
        uses: actions/cache@v5
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-cache
      - name: Install
        run: nix develop -c yarn install
      - name: Build website
        run: nix develop -c yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          user_name: 'Damian Nadales'
          user_email: damian.nadales@iohk.io
          force_orphan: true
